apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    labels:
        project: {{ .Values.labels.project }}
        tier: {{ index .Values.labels.tier 2 }}
        component: {{ index .Values.labels.component 2 }}
spec:
    replicas: 2
    selector:
        matchLabels:
          project: {{ .Values.labels.project }}
          tier: {{ index .Values.labels.tier 2 }}
          component: {{ index .Values.labels.component 2 }}
    template:
        metadata:
            labels:
              project: {{ .Values.labels.project }}
              tier: {{ index .Values.labels.tier 2 }}
              component: {{ index .Values.labels.component 2 }}
        spec:
            containers:
            - name: frontend
              image:  "{{ .Values.frontend.image }}:{{ .Values.frontend.version}}"
              volumeMounts:
                - name: {{ .Values.frontend.volumeName }}
                  mountPath: "/etc/nginx/{{ .Values.frontend.confFile }}"
                  subPath: {{ .Values.frontend.confFile }}
                  readOnly: true
              imagePullPolicy: Always
              ports:
              - containerPort: {{ .Values.frontendService.port }}
            volumes:
            - name: {{ .Values.frontend.volumeName }}
              configMap:
                name: expense-config
                items:
                - key: {{ .Values.frontend.confFile }}
                  path: {{ .Values.frontend.confFile }}
