apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.frontendService.type }}
  selector:
    project: {{ .Values.labels.project }}
    tier: {{ index .Values.labels.tier 2 }}
    component: {{ index .Values.labels.component 2 }}
  ports:
  - name: frontend-port
    protocol: "TCP"
    targetPort: {{ .Values.frontendService.port }}
    port: {{ .Values.frontendService.port }}
    nodePort: {{ .Values.frontendService.nodePort }}