labels:
  project: expense
  tier:
  - db
  - backend
  - frontend
  component:
  - mysql
  - backend
  - frontend

db:
  replicas: 2
  image: mrmotam/expense-db
  version: 0.1.0
  MYSQL_ROOT_PASSWORD: 'ExpenseApp@1'
  port: 3306

svc-db:
  serviceName: mysql
  type: None

storage-config:
  storage: 2Gi
  className: expense-storage

backend:
  replicas: 2
  image: mrmotam/expense-backend
  version: 0.1.0
  env:
  - DB_HOST: mysql
  - DB_USER: expense

svc-backend:
  port: 8080

frontend:
  replicas: 2
  image: mrmotam/expense-backend
  version: 0.1.1
  volumeName: nginx-config
  confFile: nginx.conf

svc-frontend:
  port: 80
  type: NodePort
  nodePort: 31000

config: |
  user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log notice;
    pid /run/nginx.pid;

    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        keepalive_timeout   65;
        types_hash_max_size 4096;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        include /etc/nginx/conf.d/*.conf;

        server {
            listen       80;
            listen       [::]:80;
            server_name  _;
            root         /usr/share/nginx/html;

            include /etc/nginx/default.d/*.conf;

            location / {
            try_files $uri $uri/ =404;
            }

            location /api/ { proxy_pass http://backend:8080/; 
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_read_timeout 30s;
            proxy_connect_timeout 5s;

            }
        }
    }