apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    labels:
        project: {{ .Values.labels.project }}
        tier: {{ index .Values.labels.tier 1 }}
        component: {{ index .Values.labels.component 1 }}
spec:
    replicas: {{ .Values.backend.replicas }}
    selector:
        matchLabels:
            project: {{ .Values.labels.project }}
            tier: {{ index .Values.labels.tier 1 }}
            component: {{ index .Values.labels.component 1 }}
    template:
        metadata:
            labels:
                project: {{ .Values.labels.project }}
                tier: {{ index .Values.labels.tier 1 }}
                component: {{ index .Values.labels.component 1 }}
        spec:
            containers:
            - name: backend
              image: "{{ .Values.backend.image }}:{{ .Values.backend.version}}"
              env:
              - name: DB_HOST
                value: {{ index.Values.backend.env 0 }}
              - name: DB_USER
                value: {{ index.Values.backend.env 1 }}
                  
    