apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    project: {{ .Values.labels.project }}
    tier: {{ index .Values.labels.tier 1 }}
    component: {{ index .Values.labels.component 1 }}
  ports:
  - name: backend-port
    protocol: "TCP"
    port: {{ .Values.backendService.port }}
    targetPort: {{ .Values.backendService.port }}