apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbService.serviceName }}
spec:
  clusterIP: {{ .Values.dbService.type }}
  selector:
    project: {{ .Values.labels.project }}
    tier: {{ index .Values.labels.tier 0 }}
    component: {{ index .Values.labels.component 0 }}
  ports:
    - name: mysql-port
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      protocol: TCP