apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    project: {{ .Values.labels.project }}
    tier: {{ index .Values.labels.tier 0 }}
    component: {{ index .Values.labels.component 0 }}

spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      project: {{ .Values.labels.project }}
      tier: {{ index .Values.labels.tier 0 }}
      component: {{ index .Values.labels.component 0 }}
  serviceName: {{ .Values.svc-db.serviceName }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        project: {{ .Values.labels.project }}
        tier: {{ index .Values.labels.tier 0 }}
        component: {{ index .Values.labels.component 0 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.db.image }}:{{ .Values.db.version}}"
          args:
            - --mysql-native-password=ON
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.db.MYSQL_ROOT_PASSWORD }}
          ports:
            - name: mysql-port
              containerPort: {{ .Values.db.port }}
          volumeMounts:
            - name: mysql-db
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-db
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storageConfig.className }}
        resources:
          requests:
            storage: {{ .Values.storageConfig.storage }}