apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    project: expense-app
    tier: frontend
    component: frontend
  ports:
  - name: frontend-port
    protocol: "TCP"
    targetPort: 80
    port: 80
    nodePort: 31000